title: About Me
author: Jordan Doss
email: jdoss1@ebnet.org
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my site! I am going to talk about a few things about 
  my site so that you can get to know me better!
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
